version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo Installing AWS CLI...
      - yum install -y aws-cli
  pre_build:
    commands:
      - echo Pre-build phase started...
  post_build:
    commands:
      - echo Build complete, pushing files to S3...
      - aws s3 sync . s3://profile2.0 --delete
      - echo Files successfully uploaded to S3!

artifacts:
  files:
    - '**/*'
